<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Incidents Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Incident\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE TEN TABLES THIS MODULE OWNS.
 *
 * The incident record and what hangs off it — the timeline, the parties, the
 * evidence, the money and the links between records — plus the shipped taxonomy
 * (category / sub-category) and the area-scoped taxonomy an administrator edits
 * (kind / sub-category).
 *
 * IT RUNS AFTER THE CORE, because a module's versions run after the versions of
 * every package it requires, whatever dates either of them carries. That is what
 * makes the cross-package constraints below safe to declare here: an incident is
 * filed in an AREA, may fall in a ZONE, and is recorded by a PERSON, so
 * `area_of_interest`, `zone` and `team_user` already exist by the time this runs.
 * Those three foreign keys live HERE, in the version of the package that declares
 * them, and never in the core's.
 *
 * @see vendor/uhifadhi/uhifadhi/src/Uhifadhi/Bundle/RegistryBundle/Version/DependencyOrderComparator.php
 *      — the dependency graph decides between packages; the timestamp only
 *      orders versions inside one
 */
final class Version20260910045214 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The incident register, its timeline, money and evidence, and both taxonomies';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE incident (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, reference VARCHAR(24) NOT NULL, title VARCHAR(200) NOT NULL, narrative TEXT DEFAULT NULL, assessment TEXT DEFAULT NULL, position geometry(POINT,4326) NOT NULL, status VARCHAR(255) DEFAULT \'reported\' NOT NULL, severity VARCHAR(255) DEFAULT \'moderate\' NOT NULL, source VARCHAR(255) DEFAULT \'direct\' NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, filed_for_department_id INT DEFAULT NULL, source_record_uuid UUID DEFAULT NULL, source_record_label VARCHAR(160) DEFAULT NULL, source_record_url VARCHAR(512) DEFAULT NULL, details JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, subcategory_id INT NOT NULL, zone_id INT DEFAULT NULL, reported_by_id INT DEFAULT NULL, assigned_to_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D03A11AD17F50A6 ON incident (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D03A11AAEA34913 ON incident (reference)');
        $this->addSql('CREATE INDEX idx_incident_area_status ON incident (area_id, status)');
        $this->addSql('CREATE INDEX idx_incident_reported_at ON incident (reported_at)');
        $this->addSql('CREATE INDEX IDX_3D03A11ABD0F409C ON incident (area_id)');
        $this->addSql('CREATE INDEX IDX_3D03A11A5DC6FE57 ON incident (subcategory_id)');
        $this->addSql('CREATE INDEX IDX_3D03A11A9F2C3FAB ON incident (zone_id)');
        $this->addSql('CREATE INDEX IDX_3D03A11A71CE806 ON incident (reported_by_id)');
        $this->addSql('CREATE INDEX IDX_3D03A11AF4BD7827 ON incident (assigned_to_id)');
        $this->addSql('CREATE INDEX idx_incident_position_sp ON incident USING gist (position)');
        $this->addSql('CREATE TABLE incident_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, slug VARCHAR(40) NOT NULL, label VARCHAR(80) NOT NULL, colour_key VARCHAR(16) NOT NULL, leads JSON NOT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE897DB2D17F50A6 ON incident_category (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE897DB2989D9B62 ON incident_category (slug)');
        $this->addSql('CREATE TABLE incident_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, kind VARCHAR(255) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, body TEXT NOT NULL, detail VARCHAR(300) DEFAULT NULL, actor_name VARCHAR(120) DEFAULT NULL, to_status VARCHAR(255) DEFAULT NULL, incident_id INT NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_609AA8CDD17F50A6 ON incident_event (uuid)');
        $this->addSql('CREATE INDEX idx_incident_event_incident ON incident_event (incident_id, occurred_at)');
        $this->addSql('CREATE INDEX IDX_609AA8CD59E53FB9 ON incident_event (incident_id)');
        $this->addSql('CREATE INDEX IDX_609AA8CD10DAF24A ON incident_event (actor_id)');
        $this->addSql('CREATE TABLE incident_evidence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, kind VARCHAR(255) NOT NULL, filename VARCHAR(160) NOT NULL, path VARCHAR(512) DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, byte_size INT DEFAULT NULL, thumb_key VARCHAR(512) DEFAULT NULL, captured_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, position geometry(POINT,4326) DEFAULT NULL, caption VARCHAR(200) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, incident_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F4A43363D17F50A6 ON incident_evidence (uuid)');
        $this->addSql('CREATE INDEX IDX_F4A4336359E53FB9 ON incident_evidence (incident_id)');
        $this->addSql('CREATE INDEX idx_incident_evidence_position_sp ON incident_evidence USING gist (position)');
        $this->addSql('CREATE TABLE incident_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, note VARCHAR(300) DEFAULT NULL, linked_by_name VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, incident_id INT NOT NULL, related_id INT NOT NULL, linked_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DCA0EE4ED17F50A6 ON incident_link (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_incident_link ON incident_link (incident_id, related_id)');
        $this->addSql('CREATE INDEX IDX_DCA0EE4E59E53FB9 ON incident_link (incident_id)');
        $this->addSql('CREATE INDEX IDX_DCA0EE4E4162C001 ON incident_link (related_id)');
        $this->addSql('CREATE INDEX IDX_DCA0EE4E1AE3CFF3 ON incident_link (linked_by_id)');
        $this->addSql('CREATE TABLE incident_money (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, direction VARCHAR(255) NOT NULL, currency VARCHAR(3) DEFAULT \'TZS\' NOT NULL, claimed INT DEFAULT NULL, assessed INT DEFAULT NULL, approved INT DEFAULT NULL, settled INT DEFAULT 0 NOT NULL, waived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, waived_reason VARCHAR(300) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, incident_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ECEBB18ED17F50A6 ON incident_money (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ECEBB18E59E53FB9 ON incident_money (incident_id)');
        $this->addSql('CREATE TABLE incident_party (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, role VARCHAR(255) NOT NULL, name VARCHAR(160) NOT NULL, described_as VARCHAR(200) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, incident_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D2A1EC8AD17F50A6 ON incident_party (uuid)');
        $this->addSql('CREATE INDEX IDX_D2A1EC8A59E53FB9 ON incident_party (incident_id)');
        $this->addSql('CREATE INDEX IDX_D2A1EC8AA76ED395 ON incident_party (user_id)');
        $this->addSql('CREATE TABLE incident_subcategory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, slug VARCHAR(60) NOT NULL, label VARCHAR(80) NOT NULL, money_direction VARCHAR(255) DEFAULT NULL, term_hours INT DEFAULT 72 NOT NULL, field_set JSON NOT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1F4EA25D17F50A6 ON incident_subcategory (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1F4EA25989D9B62 ON incident_subcategory (slug)');
        $this->addSql('CREATE INDEX IDX_B1F4EA2512469DE2 ON incident_subcategory (category_id)');
        $this->addSql('CREATE TABLE incident_taxonomy_kind (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, code VARCHAR(40) NOT NULL, label VARCHAR(80) NOT NULL, colour_key VARCHAR(16) NOT NULL, position INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1811FB3BD17F50A6 ON incident_taxonomy_kind (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tx_kind_area_code ON incident_taxonomy_kind (area_id, code)');
        $this->addSql('CREATE INDEX IDX_1811FB3BBD0F409C ON incident_taxonomy_kind (area_id)');
        $this->addSql('CREATE TABLE incident_taxonomy_subcategory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, code VARCHAR(60) NOT NULL, label VARCHAR(80) NOT NULL, blocks JSON NOT NULL, money_direction VARCHAR(255) DEFAULT NULL, position INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, kind_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_782CD95BD17F50A6 ON incident_taxonomy_subcategory (uuid)');
        $this->addSql('CREATE INDEX IDX_782CD95B30602CA9 ON incident_taxonomy_subcategory (kind_id)');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11ABD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11A5DC6FE57 FOREIGN KEY (subcategory_id) REFERENCES incident_subcategory (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11A9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11A71CE806 FOREIGN KEY (reported_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11AF4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_event ADD CONSTRAINT FK_609AA8CD59E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_event ADD CONSTRAINT FK_609AA8CD10DAF24A FOREIGN KEY (actor_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_evidence ADD CONSTRAINT FK_F4A4336359E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_link ADD CONSTRAINT FK_DCA0EE4E59E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_link ADD CONSTRAINT FK_DCA0EE4E4162C001 FOREIGN KEY (related_id) REFERENCES incident (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_link ADD CONSTRAINT FK_DCA0EE4E1AE3CFF3 FOREIGN KEY (linked_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_money ADD CONSTRAINT FK_ECEBB18E59E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_party ADD CONSTRAINT FK_D2A1EC8A59E53FB9 FOREIGN KEY (incident_id) REFERENCES incident (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_party ADD CONSTRAINT FK_D2A1EC8AA76ED395 FOREIGN KEY (user_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_subcategory ADD CONSTRAINT FK_B1F4EA2512469DE2 FOREIGN KEY (category_id) REFERENCES incident_category (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_taxonomy_kind ADD CONSTRAINT FK_1811FB3BBD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident_taxonomy_subcategory ADD CONSTRAINT FK_782CD95B30602CA9 FOREIGN KEY (kind_id) REFERENCES incident_taxonomy_kind (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    /**
     * The constraints first, then the tables — the reverse of the order up()
     * built them in, so nothing is dropped while something still points at it.
     *
     * This is a rollback of the CREATE, not a data-safe undo: dropping a table
     * drops its rows, and no `down()` brings those back. What it guarantees is
     * that the schema round-trips, which is what makes the upgrade rehearsal
     * worth running.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11ABD0F409C');
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11A5DC6FE57');
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11A9F2C3FAB');
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11A71CE806');
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11AF4BD7827');
        $this->addSql('ALTER TABLE incident_event DROP CONSTRAINT FK_609AA8CD59E53FB9');
        $this->addSql('ALTER TABLE incident_event DROP CONSTRAINT FK_609AA8CD10DAF24A');
        $this->addSql('ALTER TABLE incident_evidence DROP CONSTRAINT FK_F4A4336359E53FB9');
        $this->addSql('ALTER TABLE incident_link DROP CONSTRAINT FK_DCA0EE4E59E53FB9');
        $this->addSql('ALTER TABLE incident_link DROP CONSTRAINT FK_DCA0EE4E4162C001');
        $this->addSql('ALTER TABLE incident_link DROP CONSTRAINT FK_DCA0EE4E1AE3CFF3');
        $this->addSql('ALTER TABLE incident_money DROP CONSTRAINT FK_ECEBB18E59E53FB9');
        $this->addSql('ALTER TABLE incident_party DROP CONSTRAINT FK_D2A1EC8A59E53FB9');
        $this->addSql('ALTER TABLE incident_party DROP CONSTRAINT FK_D2A1EC8AA76ED395');
        $this->addSql('ALTER TABLE incident_subcategory DROP CONSTRAINT FK_B1F4EA2512469DE2');
        $this->addSql('ALTER TABLE incident_taxonomy_kind DROP CONSTRAINT FK_1811FB3BBD0F409C');
        $this->addSql('ALTER TABLE incident_taxonomy_subcategory DROP CONSTRAINT FK_782CD95B30602CA9');
        $this->addSql('DROP TABLE incident');
        $this->addSql('DROP TABLE incident_category');
        $this->addSql('DROP TABLE incident_event');
        $this->addSql('DROP TABLE incident_evidence');
        $this->addSql('DROP TABLE incident_link');
        $this->addSql('DROP TABLE incident_money');
        $this->addSql('DROP TABLE incident_party');
        $this->addSql('DROP TABLE incident_subcategory');
        $this->addSql('DROP TABLE incident_taxonomy_kind');
        $this->addSql('DROP TABLE incident_taxonomy_subcategory');
    }
}
