<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Incidents Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Incident\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE FOUR PER-AREA LISTS GET SOMEWHERE TO LIVE.
 *
 * Four questions on the report form do not hold their own words — which animal,
 * by what method, what the ground is used for, which named place — and until now
 * nothing could put any in. `incident_area_list_entry` is where they go: one row
 * per word, carrying the list it is in, the area whose word it is, a key that
 * never changes, the word itself and an optional note.
 *
 * EXPAND ONLY. A new table, no column touched on any existing one, and no data to
 * backfill: an area starts with no words, exactly as it starts with no kinds, and
 * the platform ships none and suggests none. So there is nothing here that could
 * fail on a populated database, and nothing destructive to defer.
 *
 * THE KEY IS UNIQUE WITHIN THE AREA AND THE LIST, not within the table: a
 * `water-body` named place and a `water-body` land use are two different words,
 * and two areas may each have their own `lion`. The index beside it is the one
 * every read uses — one area, one list, in order.
 *
 * NOTHING IS DELETED FROM THIS TABLE by the product: `retired_at` is how a word
 * leaves the report form, and every incident filed under it keeps it. The area
 * foreign key cascades, because a word cannot outlive the area whose word it is.
 */
final class Version20260912163000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The four per-area lists a gating question reads hold their words in a table of their own.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE incident_area_list_entry (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                list VARCHAR(24) NOT NULL,
                entry_key VARCHAR(80) NOT NULL,
                label VARCHAR(120) NOT NULL,
                note VARCHAR(160) DEFAULT NULL,
                position INT DEFAULT 0 NOT NULL,
                retired_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                area_id INT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_518035D0D17F50A6 ON incident_area_list_entry (uuid)');
        $this->addSql('CREATE INDEX idx_area_list_entry_area_list ON incident_area_list_entry (area_id, list)');
        $this->addSql('CREATE UNIQUE INDEX uniq_area_list_entry_key ON incident_area_list_entry (area_id, list, entry_key)');
        $this->addSql('CREATE INDEX IDX_518035D0BD0F409C ON incident_area_list_entry (area_id)');
        $this->addSql('ALTER TABLE incident_area_list_entry ADD CONSTRAINT FK_518035D0BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE incident_area_list_entry');
    }
}
