<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Incidents Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Incident\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE DEFERRAL IS COLLECTED: the installation-wide taxonomy leaves the database.
 *
 * `Version20260911140000` carried every incident onto its own area's words and
 * then kept `incident.subcategory_id`, `incident_subcategory` and
 * `incident_category` for one release, so an installation could read what a
 * record used to say and could roll the code back. This is that later release.
 *
 * @destructive — waits for 0.4.0, the release after the convergence shipped in
 *                0.3. It drops the two tables of the shared classification and
 *                the column that pointed at them. Everything a record was filed
 *                against is already in `incident.taxonomy_subcategory_id`, put
 *                there by Version20260911140000 and required ever since; what
 *                goes here is the copy nothing has read since that version.
 *
 * WHY IT IS SHIPPED RATHER THAN LEFT TO THE INSTALLATION. A deferral that is
 * never collected does not stay quiet: the mapping no longer knows those three
 * things, so `doctrine:migrations:diff` proposes dropping them on every
 * installation, for ever, and sooner or later somebody applies the version it
 * wrote. That version fails — the generator plans `DROP TABLE
 * incident_subcategory` while `incident.subcategory_id` still references it, and
 * PostgreSQL answers "cannot drop table incident_subcategory because other
 * objects depend on it" — and because the whole run is one transaction, every
 * later version on that installation is blocked behind it.
 *
 * THE ORDER IS THE WHOLE OF THE FIX, and it is the reverse of the one that built
 * them: the referencing key and its index first, then the column, then the key
 * between the two tables, then the tables, child before parent.
 *
 * `IF EXISTS` throughout, for the one box that already tried: an installation
 * that was handed the generated version and repaired part of it by hand still
 * arrives here, and a shipped version has to be the statement of where the
 * database ends up, not a bet on where it started.
 */
final class Version20260919210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The installation-wide taxonomy the per-area one replaced is dropped, referencing key first.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT IF EXISTS FK_3D03A11A5DC6FE57');
        $this->addSql('DROP INDEX IF EXISTS IDX_3D03A11A5DC6FE57');
        $this->addSql('ALTER TABLE incident DROP COLUMN IF EXISTS subcategory_id');

        $this->addSql('ALTER TABLE incident_subcategory DROP CONSTRAINT IF EXISTS FK_B1F4EA2512469DE2');
        $this->addSql('DROP TABLE IF EXISTS incident_subcategory');
        $this->addSql('DROP TABLE IF EXISTS incident_category');
    }

    /**
     * The tables and the column come back, empty.
     *
     * This is a rollback of the DROP, not an undo of it: the rows went with the
     * tables and no `down()` brings them back. What it guarantees is that the
     * schema round-trips, so an installation rehearsing a release downgrade
     * lands on a database the previous code can start against. `subcategory_id`
     * returns NULLABLE, which is how the version before this one left it:
     * incidents filed since the convergence never had one.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE incident_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, slug VARCHAR(40) NOT NULL, label VARCHAR(80) NOT NULL, colour_key VARCHAR(16) NOT NULL, leads JSON NOT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE897DB2D17F50A6 ON incident_category (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE897DB2989D9B62 ON incident_category (slug)');

        $this->addSql('CREATE TABLE incident_subcategory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, slug VARCHAR(60) NOT NULL, label VARCHAR(80) NOT NULL, money_direction VARCHAR(255) DEFAULT NULL, term_hours INT DEFAULT 72 NOT NULL, field_set JSON NOT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1F4EA25D17F50A6 ON incident_subcategory (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1F4EA25989D9B62 ON incident_subcategory (slug)');
        $this->addSql('CREATE INDEX IDX_B1F4EA2512469DE2 ON incident_subcategory (category_id)');
        $this->addSql('ALTER TABLE incident_subcategory ADD CONSTRAINT FK_B1F4EA2512469DE2 FOREIGN KEY (category_id) REFERENCES incident_category (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE incident ADD subcategory_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11A5DC6FE57 FOREIGN KEY (subcategory_id) REFERENCES incident_subcategory (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_3D03A11A5DC6FE57 ON incident (subcategory_id)');
    }
}
