<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Incidents Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Incident\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * WHAT ONE AREA RUNS INCIDENTS ON — the table behind the module's Settings
 * section.
 *
 * A NEW TABLE, SO THERE IS NOTHING TO BACKFILL. The expand → backfill → contract
 * rule bites where a required column lands on a populated table; here the table
 * itself is new and starts empty, and empty is the correct starting state: an
 * area with no row reads the installation's configuration, so writing a row per
 * area now would turn every untouched default into a choice somebody made.
 *
 * ITS DATE PLACES IT after this module's first migration and after every core
 * version, which is what lets the foreign key name `area_of_interest`.
 */
final class Version20260911090500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The per-area incident settings the module\'s Settings section writes.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE incident_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, currency VARCHAR(3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D80C4B6D17F50A6 ON incident_settings (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_incident_settings_area ON incident_settings (area_id)');
        $this->addSql('ALTER TABLE incident_settings ADD CONSTRAINT FK_1D80C4B6BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    /**
     * @destructive — dropping this table destroys every area's chosen currency.
     *                It is the reverse of a migration that only ever added a
     *                table, so it is safe to run back down a release, and there
     *                is nothing else it could mean.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE incident_settings DROP CONSTRAINT FK_1D80C4B6BD0F409C');
        $this->addSql('DROP TABLE incident_settings');
    }
}
