<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Incidents Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace UhifadhiLabs\Incident\Model;

use UhifadhiLabs\Incident\Entity\IncidentSubcategory;

/**
 * THE DESIGN'S SAMPLE MONTH, as data — the forty-seven incidents every widget in
 * the preset gallery repeats the numbers of.
 *
 * The gallery states them once and this table reproduces them EXACTLY:
 *
 *   47 filed · 31 still open (7 reported · 13 verified · 11 in progress)
 *   16 reached resolved · 5 closed
 *   18 conflict · 12 poaching · 9 compliance · 8 mortality
 *   TZS 8,450,000 assessed in fines, 5,900,000 collected
 *   TZS 12,400,000 claimed in compensation, 9,200,000 approved, 4,700,000 paid
 *   seven zones
 *
 * {@see \UhifadhiLabs\Incident\Tests\Unit\Model\DemoMonthTest} adds those columns
 * up and fails if a row ever drifts, because a demo that quietly stopped matching
 * the spec is worse than no demo: every screenshot in the gallery would be a
 * claim the product no longer supports.
 *
 * THIRTEEN OF THE ROWS ARE THE DESIGN'S OWN, by reference and to the word —
 * INC-0306 to INC-0318 are the incidents the register, the queue, the ageing
 * widget and the worked case file all name. The other thirty-four fill the month
 * out to the stated totals; they are ordinary conservation vocabulary and never a
 * real deployment's records.
 *
 * ONE DEPARTURE FROM THE DESIGN, and it is flagged rather than hidden: the
 * register draws INC-0317 under a sub-category called "predator presence", which
 * the reference card's sixteen do not include. The card is the model spec, so the
 * row is filed under `livestock-depredation` here. Whether "predator presence"
 * becomes a seventeenth sub-category is a ruling nobody has made.
 */
final class DemoMonth
{
    /** The month the design's sample is set in. */
    public const string MONTH = '2026-08';

    /** The seven zones the gallery names. Attached only where the host has drawn them. */
    public const array ZONES = ['Endulen', 'Lerai', 'Naabi', 'Nainokanoka', 'Olbalbal', 'Ngoitokitok', 'Kakesio'];

    /**
     * The forty-seven, oldest first — which is also reference order, because a
     * case number is issued when the report is taken.
     *
     * @return list<array{
     *     reference: string, day: int, hour: int, minute: int,
     *     subcategory: string, status: string, severity: string, zone: string,
     *     title: string, narrative: string|null, source: string,
     *     money: array{claimed: int|null, assessed: int|null, approved: int|null, settled: int|null}|null,
     *     evidence: int,
     *     parties: list<array{role: string, name: string, described: string|null}>
     * }>
     */
    public static function incidents(): array
    {
        return [
            [
                'reference' => 'INC-0272',
                'day' => 1,
                'hour' => 6,
                'minute' => 0,
                'subcategory' => 'livestock-depredation',
                'status' => 'closed',
                'severity' => 'low',
                'zone' => 'Endulen',
                'title' => 'Predator took livestock at a boma near Endulen — 1 head lost',
                'narrative' => null,
                'source' => 'radio',
                'money' => [
                    'claimed' => 330_000,
                    'assessed' => 250_000,
                    'approved' => 250_000,
                    'settled' => 250_000,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0273',
                'day' => 1,
                'hour' => 7,
                'minute' => 7,
                'subcategory' => 'bushmeat',
                'status' => 'closed',
                'severity' => 'medium',
                'zone' => 'Lerai',
                'title' => 'Dried bushmeat seized at the Lerai checkpoint — 2 kg',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 150_000,
                    'approved' => 150_000,
                    'settled' => 150_000,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0274',
                'day' => 1,
                'hour' => 8,
                'minute' => 14,
                'subcategory' => 'human-injury',
                'status' => 'closed',
                'severity' => 'high',
                'zone' => 'Naabi',
                'title' => 'Herder injured by wildlife near Naabi — 3 hospitalised',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => 370_000,
                    'assessed' => 280_000,
                    'approved' => 280_000,
                    'settled' => 280_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0275',
                'day' => 2,
                'hour' => 9,
                'minute' => 21,
                'subcategory' => 'unlicensed-operation',
                'status' => 'closed',
                'severity' => 'medium',
                'zone' => 'Nainokanoka',
                'title' => 'Unlicensed tour operation working out of Nainokanoka — 4 vehicles',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 200_000,
                    'approved' => 200_000,
                    'settled' => 200_000,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0276',
                'day' => 2,
                'hour' => 10,
                'minute' => 28,
                'subcategory' => 'livestock-depredation',
                'status' => 'closed',
                'severity' => 'low',
                'zone' => 'Olbalbal',
                'title' => 'Predator took livestock at a boma near Olbalbal — 5 head lost',
                'narrative' => null,
                'source' => 'radio',
                'money' => [
                    'claimed' => 410_000,
                    'assessed' => 310_000,
                    'approved' => 310_000,
                    'settled' => 310_000,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0277',
                'day' => 2,
                'hour' => 11,
                'minute' => 35,
                'subcategory' => 'natural-mortality',
                'status' => 'resolved',
                'severity' => 'high',
                'zone' => 'Ngoitokitok',
                'title' => 'Carcass found near Ngoitokitok, no injury pattern — 1 recorded',
                'narrative' => null,
                'source' => 'direct',
                'money' => null,
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0278',
                'day' => 3,
                'hour' => 12,
                'minute' => 42,
                'subcategory' => 'ivory-trophy',
                'status' => 'resolved',
                'severity' => 'medium',
                'zone' => 'Kakesio',
                'title' => 'Trophy pieces recovered near Kakesio — 2 items',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 250_000,
                    'approved' => 250_000,
                    'settled' => 250_000,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0279',
                'day' => 3,
                'hour' => 13,
                'minute' => 49,
                'subcategory' => 'property-damage',
                'status' => 'resolved',
                'severity' => 'medium',
                'zone' => 'Endulen',
                'title' => 'Water tank and fencing wrecked at Endulen — 3 structures',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => 450_000,
                    'assessed' => 340_000,
                    'approved' => 340_000,
                    'settled' => 340_000,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0280',
                'day' => 3,
                'hour' => 14,
                'minute' => 56,
                'subcategory' => 'livestock-depredation',
                'status' => 'resolved',
                'severity' => 'high',
                'zone' => 'Lerai',
                'title' => 'Predator took livestock at a boma near Lerai — 4 head lost',
                'narrative' => null,
                'source' => 'radio',
                'money' => [
                    'claimed' => 490_000,
                    'assessed' => 370_000,
                    'approved' => 370_000,
                    'settled' => 370_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0281',
                'day' => 4,
                'hour' => 15,
                'minute' => 3,
                'subcategory' => 'bushmeat',
                'status' => 'resolved',
                'severity' => 'low',
                'zone' => 'Naabi',
                'title' => 'Dried bushmeat seized at the Naabi checkpoint — 5 kg',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 300_000,
                    'approved' => 300_000,
                    'settled' => 300_000,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0282',
                'day' => 4,
                'hour' => 16,
                'minute' => 10,
                'subcategory' => 'human-injury',
                'status' => 'resolved',
                'severity' => 'low',
                'zone' => 'Nainokanoka',
                'title' => 'Herder injured by wildlife near Nainokanoka — 1 hospitalised',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => 530_000,
                    'assessed' => 400_000,
                    'approved' => 400_000,
                    'settled' => 400_000,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0283',
                'day' => 4,
                'hour' => 6,
                'minute' => 17,
                'subcategory' => 'unlicensed-operation',
                'status' => 'resolved',
                'severity' => 'medium',
                'zone' => 'Olbalbal',
                'title' => 'Unlicensed tour operation working out of Olbalbal — 2 vehicles',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 350_000,
                    'approved' => 350_000,
                    'settled' => 350_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0284',
                'day' => 5,
                'hour' => 7,
                'minute' => 24,
                'subcategory' => 'livestock-depredation',
                'status' => 'resolved',
                'severity' => 'high',
                'zone' => 'Ngoitokitok',
                'title' => 'Predator took livestock at a boma near Ngoitokitok — 3 head lost',
                'narrative' => null,
                'source' => 'radio',
                'money' => [
                    'claimed' => 570_000,
                    'assessed' => 430_000,
                    'approved' => 430_000,
                    'settled' => 430_000,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0285',
                'day' => 5,
                'hour' => 8,
                'minute' => 31,
                'subcategory' => 'natural-mortality',
                'status' => 'resolved',
                'severity' => 'medium',
                'zone' => 'Kakesio',
                'title' => 'Carcass found near Kakesio, no injury pattern — 4 recorded',
                'narrative' => null,
                'source' => 'direct',
                'money' => null,
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0286',
                'day' => 5,
                'hour' => 9,
                'minute' => 38,
                'subcategory' => 'ivory-trophy',
                'status' => 'in_progress',
                'severity' => 'low',
                'zone' => 'Endulen',
                'title' => 'Trophy pieces recovered near Endulen — 5 items',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 400_000,
                    'approved' => 400_000,
                    'settled' => 200_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0287',
                'day' => 6,
                'hour' => 10,
                'minute' => 45,
                'subcategory' => 'property-damage',
                'status' => 'in_progress',
                'severity' => 'high',
                'zone' => 'Lerai',
                'title' => 'Water tank and fencing wrecked at Lerai — 1 structures',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => 610_000,
                    'assessed' => 460_000,
                    'approved' => 460_000,
                    'settled' => 0,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0288',
                'day' => 6,
                'hour' => 11,
                'minute' => 52,
                'subcategory' => 'livestock-depredation',
                'status' => 'in_progress',
                'severity' => 'medium',
                'zone' => 'Naabi',
                'title' => 'Predator took livestock at a boma near Naabi — 2 head lost',
                'narrative' => null,
                'source' => 'radio',
                'money' => [
                    'claimed' => 650_000,
                    'assessed' => 490_000,
                    'approved' => 490_000,
                    'settled' => 0,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0289',
                'day' => 6,
                'hour' => 12,
                'minute' => 59,
                'subcategory' => 'bushmeat',
                'status' => 'in_progress',
                'severity' => 'medium',
                'zone' => 'Nainokanoka',
                'title' => 'Dried bushmeat seized at the Nainokanoka checkpoint — 3 kg',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 450_000,
                    'approved' => 450_000,
                    'settled' => 450_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0290',
                'day' => 7,
                'hour' => 13,
                'minute' => 6,
                'subcategory' => 'human-injury',
                'status' => 'in_progress',
                'severity' => 'high',
                'zone' => 'Olbalbal',
                'title' => 'Herder injured by wildlife near Olbalbal — 4 hospitalised',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => 330_000,
                    'assessed' => 250_000,
                    'approved' => 250_000,
                    'settled' => 0,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0291',
                'day' => 7,
                'hour' => 14,
                'minute' => 13,
                'subcategory' => 'unlicensed-operation',
                'status' => 'in_progress',
                'severity' => 'low',
                'zone' => 'Ngoitokitok',
                'title' => 'Unlicensed tour operation working out of Ngoitokitok — 5 vehicles',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 150_000,
                    'approved' => 150_000,
                    'settled' => 150_000,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0292',
                'day' => 7,
                'hour' => 15,
                'minute' => 20,
                'subcategory' => 'livestock-depredation',
                'status' => 'verified',
                'severity' => 'low',
                'zone' => 'Kakesio',
                'title' => 'Predator took livestock at a boma near Kakesio — 1 head lost',
                'narrative' => null,
                'source' => 'radio',
                'money' => [
                    'claimed' => 370_000,
                    'assessed' => 280_000,
                    'approved' => 280_000,
                    'settled' => 280_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0293',
                'day' => 8,
                'hour' => 16,
                'minute' => 27,
                'subcategory' => 'natural-mortality',
                'status' => 'verified',
                'severity' => 'medium',
                'zone' => 'Endulen',
                'title' => 'Carcass found near Endulen, no injury pattern — 2 recorded',
                'narrative' => null,
                'source' => 'direct',
                'money' => null,
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0294',
                'day' => 8,
                'hour' => 6,
                'minute' => 34,
                'subcategory' => 'ivory-trophy',
                'status' => 'verified',
                'severity' => 'high',
                'zone' => 'Lerai',
                'title' => 'Trophy pieces recovered near Lerai — 3 items',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 200_000,
                    'approved' => 200_000,
                    'settled' => 200_000,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0295',
                'day' => 8,
                'hour' => 7,
                'minute' => 41,
                'subcategory' => 'property-damage',
                'status' => 'verified',
                'severity' => 'medium',
                'zone' => 'Naabi',
                'title' => 'Water tank and fencing wrecked at Naabi — 4 structures',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => 410_000,
                    'assessed' => 310_000,
                    'approved' => 310_000,
                    'settled' => 310_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0296',
                'day' => 9,
                'hour' => 8,
                'minute' => 48,
                'subcategory' => 'livestock-depredation',
                'status' => 'verified',
                'severity' => 'low',
                'zone' => 'Nainokanoka',
                'title' => 'Predator took livestock at a boma near Nainokanoka — 5 head lost',
                'narrative' => null,
                'source' => 'radio',
                'money' => [
                    'claimed' => 450_000,
                    'assessed' => 340_000,
                    'approved' => 340_000,
                    'settled' => 340_000,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0297',
                'day' => 9,
                'hour' => 9,
                'minute' => 55,
                'subcategory' => 'bushmeat',
                'status' => 'verified',
                'severity' => 'high',
                'zone' => 'Olbalbal',
                'title' => 'Dried bushmeat seized at the Olbalbal checkpoint — 1 kg',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 250_000,
                    'approved' => 250_000,
                    'settled' => 250_000,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0298',
                'day' => 9,
                'hour' => 10,
                'minute' => 2,
                'subcategory' => 'human-injury',
                'status' => 'verified',
                'severity' => 'medium',
                'zone' => 'Ngoitokitok',
                'title' => 'Herder injured by wildlife near Ngoitokitok — 2 hospitalised',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => 2_030_000,
                    'assessed' => 1_390_000,
                    'approved' => 1_390_000,
                    'settled' => 1_390_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0299',
                'day' => 10,
                'hour' => 11,
                'minute' => 9,
                'subcategory' => 'unlicensed-operation',
                'status' => 'verified',
                'severity' => 'medium',
                'zone' => 'Kakesio',
                'title' => 'Unlicensed tour operation working out of Kakesio — 3 vehicles',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 300_000,
                    'approved' => 300_000,
                    'settled' => 300_000,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0300',
                'day' => 10,
                'hour' => 12,
                'minute' => 16,
                'subcategory' => 'roadkill',
                'status' => 'reported',
                'severity' => 'high',
                'zone' => 'Endulen',
                'title' => 'Roadkill on the Endulen road — 4 carcass removed',
                'narrative' => null,
                'source' => 'radio',
                'money' => [
                    'claimed' => null,
                    'assessed' => 350_000,
                    'approved' => 350_000,
                    'settled' => 350_000,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0301',
                'day' => 10,
                'hour' => 13,
                'minute' => 23,
                'subcategory' => 'bushmeat',
                'status' => 'reported',
                'severity' => 'low',
                'zone' => 'Lerai',
                'title' => 'Dried bushmeat seized at the Lerai checkpoint — 5 kg',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 400_000,
                    'approved' => 400_000,
                    'settled' => 400_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0302',
                'day' => 11,
                'hour' => 14,
                'minute' => 30,
                'subcategory' => 'ivory-trophy',
                'status' => 'reported',
                'severity' => 'low',
                'zone' => 'Naabi',
                'title' => 'Trophy pieces recovered near Naabi — 1 items',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 450_000,
                    'approved' => 450_000,
                    'settled' => 450_000,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0303',
                'day' => 11,
                'hour' => 15,
                'minute' => 37,
                'subcategory' => 'unlicensed-operation',
                'status' => 'reported',
                'severity' => 'medium',
                'zone' => 'Nainokanoka',
                'title' => 'Unlicensed tour operation working out of Nainokanoka — 2 vehicles',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 150_000,
                    'approved' => 150_000,
                    'settled' => 150_000,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0304',
                'day' => 12,
                'hour' => 16,
                'minute' => 44,
                'subcategory' => 'roadkill',
                'status' => 'reported',
                'severity' => 'high',
                'zone' => 'Olbalbal',
                'title' => 'Roadkill on the Olbalbal road — 3 carcass removed',
                'narrative' => null,
                'source' => 'radio',
                'money' => [
                    'claimed' => null,
                    'assessed' => 200_000,
                    'approved' => 200_000,
                    'settled' => 200_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0305',
                'day' => 12,
                'hour' => 6,
                'minute' => 51,
                'subcategory' => 'illegal-grazing',
                'status' => 'reported',
                'severity' => 'medium',
                'zone' => 'Ngoitokitok',
                'title' => 'Cattle grazing inside the Ngoitokitok line — 4 head',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 400_000,
                    'approved' => 400_000,
                    'settled' => 400_000,
                ],
                'evidence' => 0,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0306',
                'day' => 13,
                'hour' => 9,
                'minute' => 5,
                'subcategory' => 'poisoning',
                'status' => 'verified',
                'severity' => 'high',
                'zone' => 'Olbalbal',
                'title' => 'Vulture die-off at a poisoned carcass — nine birds',
                'narrative' => null,
                'source' => 'radio',
                'money' => null,
                'evidence' => 3,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0307',
                'day' => 15,
                'hour' => 8,
                'minute' => 40,
                'subcategory' => 'illegal-grazing',
                'status' => 'resolved',
                'severity' => 'low',
                'zone' => 'Kakesio',
                'title' => 'Cattle grazing inside the Kakesio line — 60 head',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 300_000,
                    'approved' => 300_000,
                    'settled' => 300_000,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0308',
                'day' => 16,
                'hour' => 22,
                'minute' => 10,
                'subcategory' => 'human-injury',
                'status' => 'in_progress',
                'severity' => 'high',
                'zone' => 'Endulen',
                'title' => 'Hyena attack on a herder at night — hospitalised at Endulen',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => 2_000_000,
                    'assessed' => 1_500_000,
                    'approved' => 1_500_000,
                    'settled' => 0,
                ],
                'evidence' => 2,
                'parties' => [
                    [
                        'role' => 'claimant',
                        'name' => 'S. Ndarai',
                        'described' => 'herder · Endulen · treated at the health centre',
                    ],
                ],
            ],
            [
                'reference' => 'INC-0309',
                'day' => 17,
                'hour' => 10,
                'minute' => 25,
                'subcategory' => 'boundary-encroachment',
                'status' => 'in_progress',
                'severity' => 'medium',
                'zone' => 'Nainokanoka',
                'title' => 'Cultivation across the Nainokanoka boundary — 3 acres',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 250_000,
                    'approved' => 250_000,
                    'settled' => 0,
                ],
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0310',
                'day' => 18,
                'hour' => 14,
                'minute' => 0,
                'subcategory' => 'ivory-trophy',
                'status' => 'verified',
                'severity' => 'high',
                'zone' => 'Naabi',
                'title' => 'Trophy pieces recovered near Naabi — 2 items',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 400_000,
                    'approved' => 400_000,
                    'settled' => 400_000,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0311',
                'day' => 19,
                'hour' => 7,
                'minute' => 15,
                'subcategory' => 'bushmeat',
                'status' => 'in_progress',
                'severity' => 'high',
                'zone' => 'Naabi',
                'title' => 'Two suspects detained at Naabi gate with 34 kg of dried bushmeat',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 900_000,
                    'approved' => 900_000,
                    'settled' => 450_000,
                ],
                'evidence' => 2,
                'parties' => [
                    [
                        'role' => 'suspect',
                        'name' => 'Two men, detained',
                        'described' => 'held at Naabi gate · statements recorded',
                    ],
                ],
            ],
            [
                'reference' => 'INC-0312',
                'day' => 19,
                'hour' => 16,
                'minute' => 45,
                'subcategory' => 'crop-raiding',
                'status' => 'verified',
                'severity' => 'medium',
                'zone' => 'Ngoitokitok',
                'title' => 'Elephant crop raid — 1.4 ha of maize destroyed overnight',
                'narrative' => null,
                'source' => 'community',
                'money' => [
                    'claimed' => 800_000,
                    'assessed' => 600_000,
                    'approved' => 600_000,
                    'settled' => 0,
                ],
                'evidence' => 2,
                'parties' => [
                    [
                        'role' => 'claimant',
                        'name' => 'E. Sanare',
                        'described' => 'household head · Ngoitokitok',
                    ],
                ],
            ],
            [
                'reference' => 'INC-0313',
                'day' => 20,
                'hour' => 5,
                'minute' => 41,
                'subcategory' => 'livestock-depredation',
                'status' => 'in_progress',
                'severity' => 'high',
                'zone' => 'Endulen',
                'title' => 'Lion killed four goats at Osinoni — compensation claim opened',
                'narrative' => 'They came in the night. The thorn fence was pushed in on the west side. Four goats dead, one dragged out and eaten. We heard nothing until the dogs. This is the third time since the rains.',
                'source' => 'direct',
                'money' => [
                    'claimed' => 1_600_000,
                    'assessed' => 1_200_000,
                    'approved' => 1_200_000,
                    'settled' => 0,
                ],
                'evidence' => 4,
                'parties' => [
                    [
                        'role' => 'claimant',
                        'name' => 'N. Olesikari',
                        'described' => 'household head · Osinoni sub-village',
                    ],
                    [
                        'role' => 'witness',
                        'name' => 'M. Kisioki',
                        'described' => 'herder, present at the boma · statement recorded',
                    ],
                    [
                        'role' => 'animal',
                        'name' => 'Lion · single adult, unmarked',
                        'described' => 'no collar; not matched to a known individual',
                    ],
                ],
            ],
            [
                'reference' => 'INC-0314',
                'day' => 21,
                'hour' => 11,
                'minute' => 5,
                'subcategory' => 'unauthorized-construction',
                'status' => 'in_progress',
                'severity' => 'medium',
                'zone' => 'Nainokanoka',
                'title' => 'Three new structures outside the agreed boma footprint',
                'narrative' => null,
                'source' => 'direct',
                'money' => [
                    'claimed' => null,
                    'assessed' => 1_200_000,
                    'approved' => 1_200_000,
                    'settled' => 0,
                ],
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0315',
                'day' => 21,
                'hour' => 16,
                'minute' => 20,
                'subcategory' => 'roadkill',
                'status' => 'resolved',
                'severity' => 'low',
                'zone' => 'Naabi',
                'title' => 'Zebra roadkill on the C-road, km 12 — carcass removed',
                'narrative' => null,
                'source' => 'radio',
                'money' => null,
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0316',
                'day' => 22,
                'hour' => 10,
                'minute' => 52,
                'subcategory' => 'natural-mortality',
                'status' => 'verified',
                'severity' => 'low',
                'zone' => 'Endulen',
                'title' => 'Wildebeest carcass, no injury pattern — natural death recorded',
                'narrative' => null,
                'source' => 'patrol_observation',
                'money' => null,
                'evidence' => 1,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0317',
                'day' => 22,
                'hour' => 8,
                'minute' => 15,
                'subcategory' => 'livestock-depredation',
                'status' => 'reported',
                'severity' => 'medium',
                'zone' => 'Endulen',
                'title' => 'Fresh lion tracks 400 m from Endulen bomas — households alerted',
                'narrative' => null,
                'source' => 'patrol_observation',
                'money' => null,
                'evidence' => 2,
                'parties' => [],
            ],
            [
                'reference' => 'INC-0318',
                'day' => 22,
                'hour' => 7,
                'minute' => 40,
                'subcategory' => 'snaring',
                'status' => 'verified',
                'severity' => 'high',
                'zone' => 'Lerai',
                'title' => 'Snare line lifted at the Lerai forest edge — 14 wire snares',
                'narrative' => null,
                'source' => 'patrol_observation',
                'money' => [
                    'claimed' => null,
                    'assessed' => 450_000,
                    'approved' => 450_000,
                    'settled' => 0,
                ],
                'evidence' => 3,
                'parties' => [],
            ],
        ];
    }

    /**
     * A point inside the sample area, deterministic per row so two runs of the
     * seeder put the same incident in the same place — a demo whose map moved
     * between runs would be read as data changing.
     *
     * The spread is a coarse lattice over the Ngorongoro bowl and its
     * surroundings; it is sample geography, not survey data, and nothing in the
     * module treats it as more than a location.
     */
    public static function positionFor(int $index): string
    {
        $latitude = -3.40 + 0.055 * ($index % 9);
        $longitude = 35.20 + 0.062 * intdiv($index, 9) + 0.011 * ($index % 5);

        return \sprintf('{"type":"Point","coordinates":[%.6F,%.6F]}', $longitude, $latitude);
    }

    /**
     * The answers to THIS sub-category's own questions — the design's "what this
     * category asks for" section, filled in.
     *
     * Only the fields the sub-category actually asks for are answered; a
     * deployment that edited its field set gets answers for whatever it kept and
     * blanks for what it added, which is the honest result of seeding against a
     * configurable taxonomy.
     *
     * @return array<string, string>
     */
    public static function detailsFor(IncidentSubcategory $subcategory, int $index): array
    {
        $answers = self::ANSWERS[$subcategory->getSlug()] ?? [];
        $details = [];
        foreach ($subcategory->getFieldSet() as $field) {
            $value = $answers[$field['key']] ?? null;
            if (null !== $value) {
                $details[$field['key']] = str_replace('%d', (string) (1 + $index % 5), $value);
            }
        }

        return $details;
    }

    /**
     * Sample answers per sub-category, keyed by the field key the taxonomy
     * installer derives from the field's label. A "%d" is replaced by a small
     * number that varies per row, so forty-seven records do not read as one
     * record copied forty-seven times.
     *
     * @var array<string, array<string, string>>
     */
    private const array ANSWERS = [
        'snaring' => ['species' => 'Impala, dik-dik', 'snares_lifted' => '%d wire snares', 'method' => 'Wire cable, anchored', 'suspects' => 'None traced', 'seizures' => 'Snares, one bicycle'],
        'bushmeat' => ['species' => 'Wildebeest, zebra', 'quantity' => '%d sacks, dried', 'method' => 'Carried on foot', 'suspects' => 'Two men, detained', 'seizures' => 'Meat, two knives'],
        'ivory-trophy' => ['species' => 'Elephant', 'trophy' => '%d worked pieces', 'method' => 'Concealed in a vehicle', 'suspects' => 'One man, detained', 'seizures' => 'Pieces, one vehicle'],
        'illegal-fishing' => ['water_body' => 'Seasonal pool', 'gear' => '%d gill nets', 'catch' => 'Tilapia, undersized', 'suspects' => 'None traced', 'seizures' => 'Nets, one canoe'],
        'livestock-depredation' => ['species' => 'Lion', 'livestock_lost' => '%d head', 'enclosure' => 'Thorn boma, breached', 'household' => 'Named on the claim', 'retaliation_risk' => 'Assessed — none observed'],
        'crop-raiding' => ['species' => 'Elephant', 'crop' => 'Maize', 'area_affected' => '%d ha', 'household' => 'Named on the claim', 'deterrents_in_place' => 'Chilli fence, partial'],
        'human-injury' => ['species' => 'Hyena', 'injuries' => 'Leg and hand', 'treatment' => 'Endulen health centre', 'household' => 'Named on the claim', 'circumstances' => 'At night, herding'],
        'property-damage' => ['species' => 'Elephant', 'property' => 'Water tank, fencing', 'extent' => '%d structures', 'household' => 'Named on the claim', 'circumstances' => 'Overnight'],
        'unauthorized-construction' => ['structures' => '%d structures', 'footprint' => 'Outside the agreed line', 'permit_status' => 'None held', 'occupier' => 'Named on the notice', 'notice_served' => 'Served on site'],
        'illegal-grazing' => ['herd_size' => '%d0 head', 'livestock_type' => 'Cattle', 'owner' => 'Named on the notice', 'duration' => 'Two nights', 'notice_served' => 'Served on site'],
        'boundary-encroachment' => ['extent' => '%d acres', 'land_use' => 'Cultivation', 'occupier' => 'Named on the notice', 'boundary_marker' => 'Beacon intact', 'notice_served' => 'Served on site'],
        'unlicensed-operation' => ['activity' => 'Guided game drives', 'operator' => 'Named on the notice', 'licence_status' => 'None held', 'vehicles' => '%d vehicles', 'notice_served' => 'Served on site'],
        'roadkill' => ['species' => 'Zebra', 'sex' => 'Female', 'age_class' => 'Adult', 'road_segment' => 'C-road, km 12', 'carcass_disposition' => 'Removed and buried', 'vehicle' => 'Not identified'],
        'natural-mortality' => ['species' => 'Wildebeest', 'sex' => 'Male', 'age_class' => 'Adult', 'condition' => 'No injury pattern', 'carcass_disposition' => 'Left in situ'],
        'disease-die-off' => ['species' => 'Wildebeest', 'individuals_affected' => '%d', 'signs' => 'Nasal discharge, lethargy', 'samples_taken' => 'Two swabs', 'carcass_disposition' => 'Burned'],
        'poisoning' => ['species' => 'White-backed vulture', 'individuals_affected' => '%d', 'suspected_agent' => 'Carbamate on a carcass', 'samples_taken' => 'Tissue and bait', 'carcass_disposition' => 'Removed and burned'],
    ];
}
